apiVersion: v1
baseDomain: shiftstack.example.com
featureSet: TechPreviewNoUpgrade
controlPlane:
  hyperthreading: Enabled
  architecture: amd64
  name: master
  platform:
    openstack:
      type: ${COMPUTE_FLAVOR}
      rootVolume:
        size: 100
        type: performance
      failureDomains:
      - computeAvailabilityZone: computeZone1
        storageAvailabilityZone: storageZone1
        portTargets:
        - id: control-plane
          network:
            id: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
          fixedIPs:
          - subnet:
              id: 11111111-1111-1111-1111-111111111111
          - subnet:
              id: 44444444-4444-4444-4444-444444444444
        - id: storage
          network:
            id: dddddddd-dddd-dddd-dddd-dddddddddddd
      - computeAvailabilityZone: computeZone2
        storageAvailabilityZone: storageZone2
        portTargets:
        - id: control-plane
          network:
            id: bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
          fixedIPs:
          - subnet:
              id: 22222222-2222-2222-2222-222222222222
          - subnet:
              id: 55555555-5555-5555-5555-555555555555
        - id: storage
          network:
            id: eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee
      - computeAvailabilityZone: computeZone3
        storageAvailabilityZone: storageZone3
        portTargets:
        - id: storage
          network:
            id: ffffffff-ffff-ffff-ffff-ffffffffffff
        - id: control-plane
          network:
            id: cccccccc-cccc-cccc-cccc-cccccccccccc
          fixedIPs:
          - subnet:
              id: 33333333-3333-3333-3333-333333333333
          - subnet:
              id: 66666666-6666-6666-6666-666666666666
  replicas: 3
compute:
- name: worker
  platform:
    openstack:
      type: ${COMPUTE_FLAVOR}
  replicas: 3
metadata:
  name: failure-domains-1
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.128.0/17
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  openstack:
    cloud: ${OS_CLOUD}
    externalNetwork: ${EXTERNAL_NETWORK}
    lbFloatingIP: ${API_FIP}
    machinesSubnet: 198.51.100.0/24
pullSecret: ${PULL_SECRET}
